### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by sheharyaar** [priyanshux/bunkmeet#1]
```console
[2022-01-27 09:21:07,433] ERROR in app: Exception on /success [POST]
Traceback (most recent call last):
  File "/home/lagnos/workspace/playground/bunkmeet/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lagnos/workspace/playground/bunkmeet/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lagnos/workspace/playground/bunkmeet/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lagnos/workspace/playground/bunkmeet/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/lagnos/workspace/playground/bunkmeet/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lagnos/workspace/playground/bunkmeet/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lagnos/workspace/playground/bunkmeet/bunkmeet/routes.py", line 67, in fetch_input
    fetch_teams = bunk(email, password)
  File "/home/lagnos/workspace/playground/bunkmeet/bunkmeet/one.py", line 27, in bunk
    driver = webdriver.Chrome(executable_path=PATH, options=options)
  File "/home/lagnos/workspace/playground/bunkmeet/venv/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/home/lagnos/workspace/playground/bunkmeet/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/lagnos/workspace/playground/bunkmeet/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/lagnos/workspace/playground/bunkmeet/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/lagnos/workspace/playground/bunkmeet/venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 88
Current browser version is 97.0.4692.99 with binary path /usr/bin/google-chrome

127.0.0.1 - - [27/Jan/2022 09:21:07] "POST /success HTTP/1.1" 500 -
```

Should I install the specific version of Chrome or will it be updated for the latest one?

```console
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 88
Current browser version is 97.0.4692.99 with binary path /usr/bin/google-chrome
```

**Comment by priyanshux** [comment]
Both should work - your chrome browser version should match with your chromedriver version.

[This commit](https://github.com/priyanshux/bunkmeet/commit/eb8505db276bc49e811c9caa43f91fb97633ee9c) should fix it with latest version. PS. I wanted to avoid hardcoding the version into the ubuntu.sh script but it showed errors back then so I let it be

**Comment by priyanshux** [comment]
Also @sheharyaar two tiny changes i never committed before - 
1. https://github.com/priyanshux/bunkmeet/commit/25e1f0ff1fe30eaf0be600f42c374c8b8894a523
2. https://github.com/priyanshux/bunkmeet/commit/f865ee5d82d58762b45150a2bd2e228ece03bb46

Update these links locally before using

**Comment by sheharyaar** [comment]
I have submitted a pr to avoid hardcoding of version, Please review it.
Thanks
